/**
 * Sprite loader and renderer for OpenClaw Pixel Agents
 *
 * Two character rendering paths:
 *   1. CharacterComposer (preferred): layers MetroCity source assets (body+hair+outfit)
 *      into unique per-agent sprites. Config-driven via CharacterRecipe.
 *   2. Legacy pre-composited: char_0..5.png sprite sheets (fallback).
 *
 * Character sprite sheet layout (legacy, 112×96):
 *   - 3 rows: down (row 0), up (row 1), right (row 2)
 *   - 7 columns per row (16×32 each):
 *     0-2: walk frames (3 unique, ping-pong 0→1→2→1)
 *     3-4: typing frames (2)
 *     5-6: reading frames (2)
 *   - "left" direction generated by horizontally flipping "right"
 */

// ── Constants ──────────────────────────────────────────────

const CHAR_FRAME_W = 16;
const CHAR_FRAME_H = 32;
const CHAR_FRAMES_PER_ROW = 7;
const CHARACTER_DIRS = ['down', 'up', 'right'] as const;
const FLOOR_TILE_SIZE = 16;

import {
  loadSourceSheets,
  composeCharacter,
  getRecipe,
  type CharacterRecipe,
  type ComposedCharacter,
} from './CharacterComposer';

// ── Types ──────────────────────────────────────────────────

export interface SpriteFrame {
  canvas: HTMLCanvasElement;
  width: number;
  height: number;
}

export interface LoadedCharacter {
  down: SpriteFrame[];
  up: SpriteFrame[];
  right: SpriteFrame[];
  left: SpriteFrame[]; // Pre-flipped for performance
}

export interface LoadedFurnitureItem {
  id: string;
  canvas: HTMLCanvasElement;
  width: number;
  height: number;
  footprintW: number;
  footprintH: number;
}

export interface LoadedFloor {
  canvas: HTMLCanvasElement;
}

// ── Asset cache ────────────────────────────────────────────

let cachedCharacters: LoadedCharacter[] = [];
let cachedFloors: LoadedFloor[] = [];
const cachedFurniture: Map<string, LoadedFurnitureItem> = new Map();
const cachedComposed: Map<string, ComposedCharacter> = new Map();

// ── Helpers ────────────────────────────────────────────────

async function loadPng(path: string, signal?: AbortSignal): Promise<ImageBitmap> {
  if (signal?.aborted) throw new DOMException('Aborted');

  const response = await fetch(path, { signal });
  if (!response.ok) throw new Error(`Failed to load ${path}: ${response.status}`);
  const blob = await response.blob();
  return createImageBitmap(blob);
}

function sliceFrame(
  bitmap: ImageBitmap,
  x: number,
  y: number,
  w: number,
  h: number,
): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(bitmap, x, y, w, h, 0, 0, w, h);
  return canvas;
}

/** Flip a canvas horizontally */
function flipHorizontal(source: HTMLCanvasElement): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = source.width;
  canvas.height = source.height;
  const ctx = canvas.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  ctx.translate(canvas.width, 0);
  ctx.scale(-1, 1);
  ctx.drawImage(source, 0, 0);
  return canvas;
}

/** Create left-facing frames by flipping right frames */
function createLeftFrames(rightFrames: SpriteFrame[]): SpriteFrame[] {
  return rightFrames.map(frame => ({
    canvas: flipHorizontal(frame.canvas),
    width: frame.width,
    height: frame.height,
  }));
}

// ── Public loaders ─────────────────────────────────────────

/**
 * Load all 6 character sprite sheets from /assets/characters/char_0..5.png
 *
 * Returns array of LoadedCharacter objects with frames for each direction.
 */
export async function loadCharacters(
  basePath = '/assets/characters/',
  signal?: AbortSignal,
): Promise<LoadedCharacter[]> {
  const characters: LoadedCharacter[] = [];

  for (let i = 0; i < 6; i++) {
    const path = `${basePath}char_${i}.png`;
    const bitmap = await loadPng(path, signal);

    const byDir: LoadedCharacter = { down: [], up: [], right: [], left: [] };

    for (let dirIdx = 0; dirIdx < CHARACTER_DIRS.length; dirIdx++) {
      const dir = CHARACTER_DIRS[dirIdx];
      const rowY = dirIdx * CHAR_FRAME_H;
      const frames: SpriteFrame[] = [];

      for (let frame = 0; frame < CHAR_FRAMES_PER_ROW; frame++) {
        const canvas = sliceFrame(
          bitmap,
          frame * CHAR_FRAME_W,
          rowY,
          CHAR_FRAME_W,
          CHAR_FRAME_H,
        );
        frames.push({ canvas, width: CHAR_FRAME_W, height: CHAR_FRAME_H });
      }

      byDir[dir] = frames;
    }

    // Pre-generate left frames from right frames
    byDir.left = createLeftFrames(byDir.right);

    characters.push(byDir);
  }

  cachedCharacters = characters;
  return characters;
}

/**
 * Load floor tiles from /assets/floors/floor_0..8.png
 */
export async function loadFloors(
  basePath = '/assets/floors/',
  signal?: AbortSignal
): Promise<LoadedFloor[]> {
  const floors: LoadedFloor[] = [];

  for (let i = 0; i < 9; i++) {
    try {
      const bitmap = await loadPng(`${basePath}floor_${i}.png`, signal);
      const canvas = document.createElement('canvas');
      canvas.width = FLOOR_TILE_SIZE;
      canvas.height = FLOOR_TILE_SIZE;
      const ctx = canvas.getContext('2d')!;
      ctx.imageSmoothingEnabled = false;
      ctx.drawImage(bitmap, 0, 0, FLOOR_TILE_SIZE, FLOOR_TILE_SIZE);
      floors.push({ canvas });
    } catch {
      // Skip missing tiles
    }
  }

  cachedFloors = floors;
  return floors;
}

/**
 * Recursively find the first leaf asset node (one with a `file` field)
 * inside a potentially nested manifest member tree (e.g. PC has
 * rotation → state → animation → asset).
 */
function findLeafAsset(node: any): { file: string; width: number; height: number; footprintW?: number; footprintH?: number } | null {
  if (node.file) return node;
  if (node.members && node.members.length > 0) {
    for (const child of node.members) {
      const leaf = findLeafAsset(child);
      if (leaf) return leaf;
    }
  }
  return null;
}

/**
 * Load furniture sprites from /assets/furniture/{TYPE}/
 * Reads manifest.json for each type to find sprite dimensions.
 */
export async function loadFurniture(
  basePath = '/assets/furniture/',
  signal?: AbortSignal,
): Promise<Map<string, LoadedFurnitureItem>> {
  const furnitureTypes = [
    'BIN', 'BOOKSHELF', 'CACTUS', 'CLOCK', 'COFFEE', 'COFFEE_TABLE',
    'CUSHIONED_BENCH', 'CUSHIONED_CHAIR', 'DESK', 'DOUBLE_BOOKSHELF',
    'HANGING_PLANT', 'LARGE_PAINTING', 'LARGE_PLANT', 'PC', 'PLANT',
    'PLANT_2', 'POT', 'SMALL_PAINTING', 'SMALL_PAINTING_2', 'SMALL_TABLE',
    'SOFA', 'TABLE_FRONT', 'WHITEBOARD', 'WOODEN_BENCH', 'WOODEN_CHAIR',
  ];

  for (const type of furnitureTypes) {
    try {
      const manifestRes = await fetch(`${basePath}${type}/manifest.json`, { signal });
      if (!manifestRes.ok) continue;

      const manifest = await manifestRes.json();

      // Find the primary (front-facing) sprite from manifest members
      let primaryFile = '';
      let fw = 0;
      let fh = 0;
      let footprintW = 1;
      let footprintH = 1;

      if (manifest.members && manifest.members.length > 0) {
        // Prefer the "front" orientation, fall back to first member
        const front = manifest.members.find(
          (m: any) => m.orientation === 'front' || m.orientation === 'front_left',
        );
        const member = front || manifest.members[0];
        // For nested groups (e.g. PC with state/animation sub-groups),
        // recursively dig to find the first leaf asset with a file
        const leaf = findLeafAsset(member);
        if (leaf) {
          primaryFile = leaf.file;
          fw = leaf.width;
          fh = leaf.height;
          footprintW = leaf.footprintW || 1;
          footprintH = leaf.footprintH || 1;
        }
      } else {
        // Simple asset — use explicit file or default to {ID}.png
        primaryFile = manifest.file || `${type}.png`;
        fw = manifest.width;
        fh = manifest.height;
        footprintW = manifest.footprintW || 1;
        footprintH = manifest.footprintH || 1;
      }

      if (!primaryFile) continue;

      const bitmap = await loadPng(`${basePath}${type}/${primaryFile}`, signal);

      // Guard dimensions — if manifest/leaf omits width/height, derive from bitmap
      if (!fw) fw = bitmap.width;
      if (!fh) fh = bitmap.height;

      cachedFurniture.set(type, {
        id: type,
        canvas: sliceFrame(bitmap, 0, 0, fw, fh),
        width: fw,
        height: fh,
        footprintW,
        footprintH,
      });
    } catch {
      // Skip broken furniture
    }
  }

  return cachedFurniture;
}

/**
 * Load all assets in parallel. Tries the paperdoll compositor first;
 * falls back to legacy pre-composited sprites if source sheets are missing.
 */
export async function loadAllAssets(signal?: AbortSignal): Promise<{
  characters: LoadedCharacter[];
  floors: LoadedFloor[];
  furniture: Map<string, LoadedFurnitureItem>;
}> {
  // Load floors and furniture independently
  const floors = await loadFloors(undefined, signal).catch(err => {
    if (err.name === 'AbortError') throw err;
    console.error('[SpriteLoader] Floor loading failed:', err);
    return [] as LoadedFloor[];
  });
  const furniture = await loadFurniture(undefined, signal).catch(err => {
    if (err.name === 'AbortError') throw err;
    console.error('[SpriteLoader] Furniture loading failed:', err);
    return new Map<string, LoadedFurnitureItem>();
  });

  // Try paperdoll compositor
  let characters: LoadedCharacter[] = [];
  try {
    await loadSourceSheets();
    cachedComposed.clear();

    // Compose characters for known agents
    const agentIds = ['main', 'cybera', 'chi', 'descartes', 'cyberlogis', 'cylena', 'sysauxilia', 'miku'];
    for (const id of agentIds) {
      const recipe = getRecipe(id);
      const composed = composeCharacter(recipe);
      cachedComposed.set(id, composed);
    }

    // Convert first composed character to legacy format for the default character set
    // (the engine still uses numeric indexing for "which sprite to use")
    characters = Array.from(cachedComposed.values()).map(composedToLoaded);

    console.log(`[SpriteLoader] Composed ${cachedComposed.size} characters from source sheets`);
  } catch (err) {
    console.warn('[SpriteLoader] Compositor failed, falling back to pre-composited sprites:', err);
    characters = await loadCharacters(undefined, signal).catch(err2 => {
      if (err2.name === 'AbortError') throw err2;
      console.error('[SpriteLoader] Legacy character loading also failed:', err2);
      return [] as LoadedCharacter[];
    });
  }

  cachedCharacters = characters;

  console.log(
    `[SpriteLoader] Assets loaded: ${characters.length} characters, ${floors.length} floors, ${furniture.size} furniture types`,
  );

  return { characters, floors, furniture };
}

/**
 * Convert a ComposedCharacter (from CharacterComposer) to the LoadedCharacter
 * format expected by the engine and getSpriteFrame().
 */
function composedToLoaded(composed: ComposedCharacter): LoadedCharacter {
  const toFrames = (canvases: HTMLCanvasElement[]): SpriteFrame[] =>
    canvases.map(canvas => ({ canvas, width: OUT_FRAME_W, height: OUT_FRAME_H }));

  const rightFrames = toFrames(composed.right);

  // The compositor outputs are already in the correct format (3 dirs × 7 frames)
  return {
    down: toFrames(composed.down),
    up: toFrames(composed.up),
    right: rightFrames,
    left: createLeftFrames(rightFrames), // Pre-flip left frames
  };
}

const OUT_FRAME_W = 16;
const OUT_FRAME_H = 32;

// ── Frame access helpers ───────────────────────────────────

export type AnimState = 'walk' | 'typing' | 'reading' | 'idle';
export type Direction = 'down' | 'up' | 'left' | 'right';

/** Frame index ranges within each direction's 7-frame row */
const FRAME_RANGES: Record<AnimState, [number, number]> = {
  idle:    [0, 1],    // frame 0 only (single standing frame)
  walk:    [0, 3],    // frames 0-2 (3 unique, used as 0,1,2,1)
  typing:  [3, 2],    // frames 3-4
  reading: [5, 2],    // frames 5-6
};

/**
 * Get the correct sprite frame canvas for a character's current state.
 */
export function getSpriteFrame(
  character: LoadedCharacter,
  state: AnimState,
  dir: Direction,
  frameTick: number,
): HTMLCanvasElement | null {
  const [startIdx, count] = FRAME_RANGES[state];
  const frameIdx = startIdx + (frameTick % count);

  // All directions now have pre-cached frames
  const frame = character[dir]?.[frameIdx];
  return frame?.canvas ?? null;
}

/** Access cached characters */
export function getCachedCharacters(): LoadedCharacter[] {
  return cachedCharacters;
}

/** Access cached furniture */
export function getCachedFurniture(): Map<string, LoadedFurnitureItem> {
  return cachedFurniture;
}

/** Access a composed character portrait by agent ID */
export function getComposedPortrait(agentId: string): HTMLCanvasElement | null {
  return cachedComposed.get(agentId)?.portrait ?? null;
}

/** Get the composed character for a specific agent */
export function getComposedCharacter(agentId: string): ComposedCharacter | null {
  return cachedComposed.get(agentId) ?? null;
}

/**
 * Recompose a single agent's character (e.g. after recipe change).
 * Returns the new LoadedCharacter for engine update.
 */
export function recomposeAgent(agentId: string, recipe: CharacterRecipe): LoadedCharacter | null {
  try {
    const composed = composeCharacter(recipe);
    cachedComposed.set(agentId, composed);
    return composedToLoaded(composed);
  } catch (err) {
    console.error(`[SpriteLoader] Failed to recompose ${agentId}:`, err);
    return null;
  }
}
