/**
 * Sprite loader and renderer for OpenClaw Pixel Agents
 *
 * Loads character sprite sheets, furniture PNGs, and floor tiles from assets.
 *
 * Character sprite sheet layout (112×96):
 *   - 3 rows: down (row 0), up (row 1), right (row 2)
 *   - 7 columns per row (16×32 each):
 *     0-2: walk frames (3 unique, ping-pong 0→1→2→1)
 *     3-4: typing frames (2)
 *     5-6: reading frames (2)
 *   - "left" direction generated by horizontally flipping "right"
 */

// ── Constants ──────────────────────────────────────────────

const CHAR_FRAME_W = 16;
const CHAR_FRAME_H = 32;
const CHAR_FRAMES_PER_ROW = 7;
const CHARACTER_DIRS = ['down', 'up', 'right'] as const;
const FLOOR_TILE_SIZE = 16;

// ── Types ──────────────────────────────────────────────────

export interface SpriteFrame {
  canvas: HTMLCanvasElement;
  width: number;
  height: number;
}

export interface LoadedCharacter {
  down: SpriteFrame[];
  up: SpriteFrame[];
  right: SpriteFrame[];
}

export interface LoadedFurnitureItem {
  id: string;
  canvas: HTMLCanvasElement;
  width: number;
  height: number;
  footprintW: number;
  footprintH: number;
}

export interface LoadedFloor {
  canvas: HTMLCanvasElement;
}

// ── Asset cache ────────────────────────────────────────────

let cachedCharacters: LoadedCharacter[] = [];
let cachedFloors: LoadedFloor[] = [];
const cachedFurniture: Map<string, LoadedFurnitureItem> = new Map();

// ── Helpers ────────────────────────────────────────────────

async function loadPng(path: string, signal?: AbortSignal): Promise<ImageBitmap> {
  if (signal?.aborted) throw new DOMException('Aborted');

  const response = await fetch(path, { signal });
  if (!response.ok) throw new Error(`Failed to load ${path}: ${response.status}`);
  const blob = await response.blob();
  return createImageBitmap(blob);
}

function sliceFrame(
  bitmap: ImageBitmap,
  x: number,
  y: number,
  w: number,
  h: number,
): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  ctx.drawImage(bitmap, x, y, w, h, 0, 0, w, h);
  return canvas;
}

/** Flip a canvas horizontally */
function flipHorizontal(source: HTMLCanvasElement): HTMLCanvasElement {
  const canvas = document.createElement('canvas');
  canvas.width = source.width;
  canvas.height = source.height;
  const ctx = canvas.getContext('2d')!;
  ctx.imageSmoothingEnabled = false;
  ctx.translate(canvas.width, 0);
  ctx.scale(-1, 1);
  ctx.drawImage(source, 0, 0);
  return canvas;
}

// ── Public loaders ─────────────────────────────────────────

/**
 * Load all 6 character sprite sheets from /assets/characters/char_0..5.png
 *
 * Returns array of LoadedCharacter objects with frames for each direction.
 */
export async function loadCharacters(
  basePath = '/assets/characters/',
  signal?: AbortSignal,
): Promise<LoadedCharacter[]> {
  const characters: LoadedCharacter[] = [];

  for (let i = 0; i < 6; i++) {
    const path = `${basePath}char_${i}.png`;
    const bitmap = await loadPng(path, signal);

    const byDir: LoadedCharacter = { down: [], up: [], right: [] };

    for (let dirIdx = 0; dirIdx < CHARACTER_DIRS.length; dirIdx++) {
      const dir = CHARACTER_DIRS[dirIdx];
      const rowY = dirIdx * CHAR_FRAME_H;
      const frames: SpriteFrame[] = [];

      for (let frame = 0; frame < CHAR_FRAMES_PER_ROW; frame++) {
        const canvas = sliceFrame(
          bitmap,
          frame * CHAR_FRAME_W,
          rowY,
          CHAR_FRAME_W,
          CHAR_FRAME_H,
        );
        frames.push({ canvas, width: CHAR_FRAME_W, height: CHAR_FRAME_H });
      }

      byDir[dir] = frames;
    }

    characters.push(byDir);
  }

  cachedCharacters = characters;
  return characters;
}

/**
 * Load floor tiles from /assets/floors/floor_0..8.png
 */
export async function loadFloors(
  basePath = '/assets/floors/',
  signal?: AbortSignal
): Promise<LoadedFloor[]> {
  const floors: LoadedFloor[] = [];

  for (let i = 0; i < 9; i++) {
    try {
      const bitmap = await loadPng(`${basePath}floor_${i}.png`, signal);
      const canvas = document.createElement('canvas');
      canvas.width = FLOOR_TILE_SIZE;
      canvas.height = FLOOR_TILE_SIZE;
      const ctx = canvas.getContext('2d')!;
      ctx.imageSmoothingEnabled = false;
      ctx.drawImage(bitmap, 0, 0, FLOOR_TILE_SIZE, FLOOR_TILE_SIZE);
      floors.push({ canvas });
    } catch {
      // Skip missing tiles
    }
  }

  cachedFloors = floors;
  return floors;
}

/**
 * Load furniture sprites from /assets/furniture/{TYPE}/
 * Reads manifest.json for each type to find sprite dimensions.
 */
export async function loadFurniture(
  basePath = '/assets/furniture/',
  signal?: AbortSignal,
): Promise<Map<string, LoadedFurnitureItem>> {
  const furnitureTypes = [
    'BIN', 'BOOKSHELF', 'CACTUS', 'CLOCK', 'COFFEE', 'COFFEE_TABLE',
    'CUSHIONED_BENCH', 'CUSHIONED_CHAIR', 'DESK', 'DOUBLE_BOOKSHELF',
    'HANGING_PLANT', 'LARGE_PAINTING', 'LARGE_PLANT', 'PC', 'PLANT',
    'PLANT_2', 'POT', 'SMALL_PAINTING', 'SMALL_PAINTING_2', 'SMALL_TABLE',
    'SOFA', 'TABLE_FRONT', 'WHITEBOARD', 'WOODEN_BENCH', 'WOODEN_CHAIR',
  ];

  for (const type of furnitureTypes) {
    try {
      const manifestRes = await fetch(`${basePath}${type}/manifest.json`, { signal });
      if (!manifestRes.ok) continue;

      const manifest = await manifestRes.json();

      // Find the primary (front-facing) sprite from manifest members
      let primaryFile = '';
      let fw = 0;
      let fh = 0;
      let footprintW = 1;
      let footprintH = 1;

      if (manifest.members && manifest.members.length > 0) {
        // Prefer the "front" orientation, fall back to first member
        const front = manifest.members.find(
          (m: any) => m.orientation === 'front' || m.orientation === 'front_left',
        );
        const member = front || manifest.members[0];
        primaryFile = member.file;
        fw = member.width;
        fh = member.height;
        footprintW = member.footprintW || 1;
        footprintH = member.footprintH || 1;
      } else if (manifest.file) {
        primaryFile = manifest.file;
        fw = manifest.width;
        fh = manifest.height;
      }

      if (!primaryFile) continue;

      const bitmap = await loadPng(`${basePath}${type}/${primaryFile}`, signal);
      cachedFurniture.set(type, {
        id: type,
        canvas: sliceFrame(bitmap, 0, 0, fw, fh),
        width: fw,
        height: fh,
        footprintW,
        footprintH,
      });
    } catch {
      // Skip broken furniture
    }
  }

  return cachedFurniture;
}

/**
 * Load all assets in parallel
 */
export async function loadAllAssets(signal?: AbortSignal): Promise<{
  characters: LoadedCharacter[];
  floors: LoadedFloor[];
  furniture: Map<string, LoadedFurnitureItem>;
}> {
  // Load each independently so one failure doesn't kill the others
  const characters = await loadCharacters(undefined, signal).catch(err => {
    if (err.name === 'AbortError') throw err;
    console.error('[SpriteLoader] Character loading failed:', err);
    return [] as LoadedCharacter[];
  });
  const floors = await loadFloors(undefined, signal).catch(err => {
    if (err.name === 'AbortError') throw err;
    console.error('[SpriteLoader] Floor loading failed:', err);
    return [] as LoadedFloor[];
  });
  const furniture = await loadFurniture(undefined, signal).catch(err => {
    if (err.name === 'AbortError') throw err;
    console.error('[SpriteLoader] Furniture loading failed:', err);
    return new Map<string, LoadedFurnitureItem>();
  });

  console.log(
    `[SpriteLoader] Assets loaded: ${characters.length} characters, ${floors.length} floors, ${furniture.size} furniture types`,
  );

  return { characters, floors, furniture };
}

// ── Frame access helpers ───────────────────────────────────

export type AnimState = 'walk' | 'typing' | 'reading';
export type Direction = 'down' | 'up' | 'left' | 'right';

/** Frame index ranges within each direction's 7-frame row */
const FRAME_RANGES: Record<AnimState, [number, number]> = {
  walk: [0, 3],    // frames 0-2 (3 unique, used as 0,1,2,1)
  typing: [3, 2],  // frames 3-4
  reading: [5, 2], // frames 5-6
};

/**
 * Get the correct sprite frame canvas for a character's current state.
 */
export function getSpriteFrame(
  character: LoadedCharacter,
  state: AnimState,
  dir: Direction,
  frameTick: number,
): HTMLCanvasElement {
  const [startIdx, count] = FRAME_RANGES[state];
  const frameIdx = startIdx + (frameTick % count);

  // "left" is "right" flipped horizontally
  if (dir === 'left') {
    const rightFrame = character.right[frameIdx];
    return flipHorizontal(rightFrame.canvas);
  }

  const dirFrames = character[dir as 'down' | 'up' | 'right'];
  return dirFrames[frameIdx].canvas;
}

/** Access cached characters */
export function getCachedCharacters(): LoadedCharacter[] {
  return cachedCharacters;
}
