import { afterEach, describe, expect, it, vi } from "vitest";
import { newEntityId } from "./id";

describe("newEntityId", () => {
  afterEach(() => {
    vi.restoreAllMocks();
    vi.unstubAllGlobals();
  });

  it("prefixes IDs generated by crypto.randomUUID", () => {
    vi.stubGlobal("crypto", {
      randomUUID: vi.fn(() => "uuid-value"),
    });

    expect(newEntityId("desk")).toBe("desk-uuid-value");
  });

  it("falls back to crypto.getRandomValues when randomUUID is unavailable", () => {
    const getRandomValues = vi.fn((bytes: Uint8Array) => {
      bytes.set(Array.from({ length: bytes.length }, (_, index) => index));
      return bytes;
    });
    vi.stubGlobal("crypto", { getRandomValues });

    expect(newEntityId("desk")).toBe("desk-000102030405060708090a0b0c0d0e0f");
    expect(getRandomValues).toHaveBeenCalledWith(expect.any(Uint8Array));
  });

  it("uses a fixed-length Math.random fallback only when Web Crypto is unavailable", () => {
    vi.stubGlobal("crypto", undefined);
    const values = [0, 0.123456789, 0.987654321, 0.555555555];
    const randomSpy = vi.spyOn(Math, "random").mockImplementation(() => values.shift() ?? 0.5);

    const id = newEntityId("desk");

    expect(id).toMatch(/^desk-[a-z0-9]{13}$/);
    expect(randomSpy).toHaveBeenCalledTimes(3);
  });
});
